# Site settings
language:               "en"
title:                  ""
description:            ""
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
#  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "/blog/"
  
# Plugins
gems:             ["jekyll-sitemap"]
plugins_dir:
  - jekyll-sitemap

# Conversion
incremental:      true

# Serving
# url:            "http://127.0.0.1.xip.io:3003"
url: "https://signup.realization.com"
# url:            "https://mutinylabs.github.io/Realization/"
# url:            "https://adityanayak.github.io/rz/"
# baseurl:        "mutiny" # does not include hostname

# Outputting
permalink:        ":title/"
# paginate_path:    "/blog/page:num"
# paginate:         5
